import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from '../lib/form-validation';
import { zodResolver } from '@hookform/resolvers/zod';
import { service } from '../lib/service';
import { Icon, Notice, Toggle } from '../components/ui';
import { errorMessage } from './session';

export type BirthLocation = { providerId?: string; name: string; country?: string; admin1?: string; latitude: number; longitude: number; timezone: string };
export type BirthInputValue = { calendarType: 'SOLAR' | 'LUNAR'; leapMonth: boolean; birthDate: string; birthTime: string | null; birthTimeUnknown: boolean; location: BirthLocation; gender: 'MALE' | 'FEMALE' | null };
const formSchema = z.object({ birthDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, '생년월일을 YYYY-MM-DD 형식으로 입력해 주세요.'), birthTime: z.string(), calendarType: z.enum(['SOLAR','LUNAR']), gender: z.enum(['','MALE','FEMALE']) }).superRefine((data,context)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(data.birthDate))return;const [year,month,day]=data.birthDate.split('-').map(Number);const solar=new Date(Date.UTC(year,month-1,day));if(year<100||month<1||month>12||day<1||(data.calendarType==='LUNAR'?day>30:solar.getUTCFullYear()!==year||solar.getUTCMonth()!==month-1||solar.getUTCDate()!==day))context.addIssue({code:'custom',path:['birthDate'],message:'선택한 달력에서 가능한 날짜를 입력해 주세요.'});});
export function BirthInputForm({ pending, onSubmit, label = '나의 사주 이야기', other = false, initial, showSave = true }: { pending: boolean; onSubmit: (input: BirthInputValue, save: boolean) => void; label?: string; other?: boolean; initial?: BirthInputValue; showSave?: boolean }) {
  const { register, handleSubmit, watch, formState: { errors } } = useForm<z.infer<typeof formSchema>>({ resolver: zodResolver(formSchema), defaultValues: { birthDate: initial?.birthDate || '', birthTime: initial?.birthTime || '', calendarType: initial?.calendarType || 'SOLAR', gender: initial?.gender || '' } });
  const [unknown, setUnknown] = useState(initial?.birthTimeUnknown || false); const [leap, setLeap] = useState(initial?.leapMonth || false); const [save, setSave] = useState(!showSave); const [query, setQuery] = useState(initial?.location.name || ''); const [selected, setSelected] = useState<BirthLocation | null>(initial?.location || null); const [locations, setLocations] = useState<BirthLocation[]>([]); const [searching, setSearching] = useState(false); const [error, setError] = useState<string | null>(null); const calendarType = watch('calendarType');
  useEffect(() => { if (selected || query.trim().length < 2) { setLocations([]); setSearching(false); return; } let active = true; const timer = setTimeout(async () => { setSearching(true); setError(null); try { const result = await service.execute<{ locations: BirthLocation[] }>('saju', { action: 'RESOLVE_LOCATION', query: query.trim(), limit: 8 }); if (result.ok && active) { setLocations(result.data.locations); if (!result.data.locations.length) setError('해당 도시를 찾지 못했어요. 영문 도시명으로도 검색해 보세요.'); } } catch (err) { if (active) setError(errorMessage(err)); } finally { if (active) setSearching(false); } }, 400); return () => { active = false; clearTimeout(timer); }; }, [query, selected]);
  const submit = handleSubmit((data) => { setError(null); if (!selected) { setError('검색 결과에서 출생도시를 선택해 주세요.'); return; } if (!unknown && !data.birthTime) { setError('출생시간을 입력하거나 ‘시간을 몰라요’를 선택해 주세요.'); return; } onSubmit({ birthDate: data.birthDate, birthTime: unknown ? null : data.birthTime, birthTimeUnknown: unknown, calendarType: data.calendarType, leapMonth: data.calendarType === 'LUNAR' && leap, gender: data.gender || null, location: selected }, save); });
  return <form onSubmit={submit}><p style={{ marginBottom: 24 }}>{showSave ? '태어난 날의 흐름을 살펴볼게요. 시간은 몰라도 괜찮아요. 확인할 수 없는 부분은 그대로 알려드려요.' : '다음 상담에서 사용할 출생 정보를 직접 저장해요. 이 화면에서는 사주를 계산하지 않아요.'}</p><div className="field-grid"><label className="field"><span>생년월일</span><input type={calendarType === 'LUNAR' ? 'text' : 'date'} inputMode={calendarType === 'LUNAR' ? 'numeric' : undefined} placeholder="YYYY-MM-DD" {...register('birthDate')} max={new Date().toISOString().slice(0,10)} />{errors.birthDate && <span className="field-error">{errors.birthDate.message}</span>}</label><label className="field"><span>달력 기준</span><select {...register('calendarType')}><option value="SOLAR">양력</option><option value="LUNAR">음력</option></select></label></div>{calendarType === 'LUNAR' && <Toggle label="윤달에 태어났어요" checked={leap} onChange={setLeap} />}<div className="field-grid"><label className="field"><span>출생시간</span><input type="time" {...register('birthTime')} disabled={unknown} /><small>정확하지 않다면 시간 모름을 선택해 주세요.</small></label><label className="field"><span>성별 <small>계산 기준 · 선택</small></span><select {...register('gender')}><option value="">아직 선택하지 않을게요</option><option value="FEMALE">여성</option><option value="MALE">남성</option></select></label></div><Toggle label="출생시간을 몰라요" checked={unknown} onChange={setUnknown} description="임의의 시간을 넣지 않고, 가능한 범위와 불확실성을 함께 표시해요." /><label className="field" style={{ marginTop: 24 }}><span>출생도시</span><input value={query} onChange={(e) => { setQuery(e.target.value); setSelected(null); }} placeholder="예: 서울, 부산, Tokyo" autoComplete="off" maxLength={100} /><small>{selected ? `${selected.name} · ${selected.timezone} 선택됨` : searching ? '도시를 찾고 있어요…' : '도시 이름을 두 글자 이상 입력하고 검색 결과를 선택해 주세요.'}</small></label>{locations.length > 0 && <ul className="location-results" aria-label="출생도시 검색 결과">{locations.map((location, i) => <li key={`${location.name}-${i}`}><button type="button" onClick={() => { setSelected(location); setQuery(location.name); setLocations([]); }}>{location.name}<small>{[location.admin1,location.country,location.timezone].filter(Boolean).join(' · ')}</small></button></li>)}</ul>}{showSave && <Toggle label={other ? '다음에도 이 사람의 정보를 기억해 주세요' : '다음에도 사용할 수 있도록 출생 정보 저장'} description={other ? '선택하지 않으면 정확한 출생 정보는 장기 저장하지 않아요.' : '저장하지 않아도 이번 상담의 계산 결과는 기록에 남아요.'} checked={save} onChange={setSave} />}{error && <Notice tone="error">{error}</Notice>}<button className="button primary wide" type="submit" disabled={pending || searching} style={{ marginTop: 24 }}>{pending ? '태어난 날의 흐름을 살펴보고 있어요…' : label}<Icon name="arrow" /></button><p className="birth-form-note">도시 검색: Open-Meteo / GeoNames. 출생도시의 시간대와 태양의 움직임을 반영해요. 날짜가 바뀌는 시간에 가까우면 가능한 범위를 함께 안내해요. <Link to="/privacy">개인정보 처리 안내</Link></p></form>;
}
