import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { service } from '../lib/service';
import { Icon, Notice } from '../components/ui';
import { BirthInputForm, type BirthInputValue } from './BirthInput';
import { errorMessage, useSession } from './session';

export function SajuEntryForm({pending,onSubmit,onStored,label}:{pending:boolean;onSubmit:(input:BirthInputValue,save:boolean)=>void;onStored:(id:string)=>void;label?:string}) {const {session}=useSession();const [manual,setManual]=useState(false);const profiles=useQuery({queryKey:['birth-profiles',session?.user.id],queryFn:()=>service.listBirthProfiles(),enabled:!!session});const own=(profiles.data||[]).filter((profile)=>profile.owner_type==='USER');if(profiles.isLoading)return <p className="muted">저장한 출생 정보를 확인하고 있어요…</p>;return <>{profiles.error&&<Notice tone="error">{errorMessage(profiles.error)}</Notice>}{!manual&&own.length?<><p style={{marginBottom:24}}>직접 저장한 출생 정보로 이어서 볼까요? 저장 당시 선택한 도시와 시간대를 그대로 사용해요.</p><div className="saved-birth-options">{own.map((profile)=><button className="saved-birth-option" key={profile.id} disabled={pending} onClick={()=>onStored(profile.id)}><Icon name="moon"/><span><strong>{profile.birth_date} · {profile.calendar_type==='LUNAR'?'음력':'양력'}{profile.leap_month?' 윤달':''}</strong><small>{profile.unknown_birth_time?'시간 모름':profile.birth_time?.slice(0,5)} · {profile.city}</small><em>{label||'이 정보로 사주 보기'}</em></span><Icon name="arrow" size={18}/></button>)}</div><div className="form-actions"><button className="button secondary" onClick={()=>setManual(true)}>다른 정보로 보기</button><Link className="button ghost" to="/profile">저장한 정보 관리 <Icon name="arrow" size={15}/></Link></div></>:<><BirthInputForm pending={pending} onSubmit={onSubmit} label={label}/>{own.length>0&&<button className="button ghost" onClick={()=>setManual(false)}><Icon name="back" size={16}/>저장한 정보에서 고르기</button>}</>}</>;}

export function RelatedBirthEntry({pending,onStored,onSubmit}:{pending:boolean;onStored:(personId:string)=>void;onSubmit:(alias:string,input:BirthInputValue,save:boolean)=>void}) {const {session}=useSession();const [manual,setManual]=useState(false);const [alias,setAlias]=useState('');const profiles=useQuery({queryKey:['birth-profiles',session?.user.id],queryFn:()=>service.listBirthProfiles(),enabled:!!session});const people=useQuery({queryKey:['related-people',session?.user.id],queryFn:()=>service.listRelatedPeople(),enabled:!!session});const saved=(people.data||[]).filter((person)=>profiles.data?.some((profile)=>profile.owner_type==='RELATED_PERSON'&&profile.related_person_id===person.id));if(profiles.isLoading||people.isLoading)return <p className="muted">따로 저장한 상대 정보를 확인하고 있어요…</p>;return <>{(profiles.error||people.error)&&<Notice tone="error">{errorMessage(profiles.error||people.error)}</Notice>}{!manual&&saved.length?<><p style={{marginBottom:24}}>출생 정보 저장을 직접 선택했던 사람과 이어서 볼 수 있어요.</p><div className="saved-birth-options">{saved.map((person)=><button className="saved-birth-option" key={person.id} disabled={pending} onClick={()=>onStored(person.id)}><Icon name="user"/><span><strong>{person.display_name}</strong><small>{person.relation||'따로 저장한 사람'}</small><em>저장한 정보로 두 사람의 궁합 보기</em></span><Icon name="arrow" size={18}/></button>)}</div><button className="button secondary" style={{marginTop:24}} onClick={()=>setManual(true)}>다른 사람의 정보 입력</button></>:<><label className="field"><span>상대의 이름 또는 별칭</span><input value={alias} onChange={(e)=>setAlias(e.target.value)} placeholder="편하게 부르는 이름" maxLength={40} required/></label><BirthInputForm other pending={pending||!alias.trim()} label="두 사람의 흐름 살펴보기" onSubmit={(input,save)=>{if(alias.trim())onSubmit(alias.trim(),input,save);}}/>{saved.length>0&&<button className="button ghost" onClick={()=>setManual(false)}><Icon name="back" size={16}/>저장한 사람에서 고르기</button>}</>}</>;}
