import { useState } from 'react';
import { Icon, Notice } from '../components/ui';
import type { BirthInputValue } from './BirthInput';
import { SajuEntryForm, RelatedBirthEntry } from './BirthEntry';

export type CompatibilityInputs = { personA: { birthProfileId: string|null; input?: BirthInputValue; saveProfile: boolean }; personB: { relatedPersonId: string|null; alias?: string; input?: BirthInputValue; saveRelatedPerson: boolean } };
export function CompatibilityForm({ pending, sajuAvailable, onTarot, onSaju, defaultMode='tarot', defaultQuestion='' }: { pending: boolean; sajuAvailable: boolean; onTarot: (alias: string, question: string) => void; onSaju: (input: CompatibilityInputs) => void; defaultMode?:'tarot'|'saju';defaultQuestion?:string }) {
  const [mode,setMode]=useState<'tarot'|'saju'>(defaultMode);const [alias,setAlias]=useState('');const [question,setQuestion]=useState(defaultQuestion);const [personA,setPersonA]=useState<CompatibilityInputs['personA']|null>(null);
  return <><div className="tab-bar"><button className={mode==='tarot'?'active':''} onClick={()=>setMode('tarot')}>지금의 관계 · 타로</button><button className={mode==='saju'?'active':''} onClick={()=>setMode('saju')}>오래 이어질 흐름 · 사주</button></div><p style={{marginBottom:24}}>마음을 단정하기보다, 서로를 이해하는 작은 실마리를 찾아봐요.</p>{mode==='tarot'?<form onSubmit={(e)=>{e.preventDefault();onTarot(alias.trim(),question.trim()||'우리 둘의 관계 흐름이 궁금해');}}><div className="tarot-preview" aria-hidden="true"><img src="/assets/tarot/back.png" alt=""/><img src="/assets/tarot/back.png" alt=""/><img src="/assets/tarot/back.png" alt=""/></div><label className="field"><span>누구와의 이야기를 볼까요?</span><input value={alias} onChange={(e)=>setAlias(e.target.value)} placeholder="이름 대신 별칭도 좋아요" maxLength={40} required/></label><label className="field"><span>지금 가장 궁금한 것 <small>선택</small></span><textarea value={question} onChange={(e)=>setQuestion(e.target.value)} placeholder="우리 사이의 분위기가 달라진 것 같아…" rows={3} maxLength={4000}/></label><button className="button primary wide" disabled={pending||!alias.trim()}>{pending?'두 사람의 카드를 펼치고 있어요…':'관계 타로 세 장 펼치기'}<Icon name="arrow"/></button></form>:!sajuAvailable?<Notice>사주 상담을 준비하고 있어요. 지금은 관계 타로로 두 사람의 이야기를 함께 살펴볼 수 있어요.</Notice>:!personA?<><div className="compatibility-step">01 · 나의 출생 정보 <span>02 · 상대의 출생 정보</span></div><SajuEntryForm pending={pending} label="상대 이야기로 넘어가기" onSubmit={(input,saveProfile)=>setPersonA({birthProfileId:null,input,saveProfile})} onStored={(birthProfileId)=>setPersonA({birthProfileId,saveProfile:false})}/></>:<><div className="compatibility-step"><button onClick={()=>setPersonA(null)}><Icon name="back" size={16}/></button><span>01 · 나의 출생 정보</span>02 · 상대의 출생 정보</div><RelatedBirthEntry pending={pending} onStored={(relatedPersonId)=>onSaju({personA,personB:{relatedPersonId,saveRelatedPerson:false}})} onSubmit={(alias,input,saveRelatedPerson)=>onSaju({personA,personB:{relatedPersonId:null,alias,input,saveRelatedPerson}})}/></>}</>;
}
