import { Link } from 'react-router-dom';
import type { SajuCurrentFlow } from '../../supabase/functions/_shared/contracts';
import type { FullSajuResult } from '../../supabase/functions/_shared/domain/full-saju';
import { Eyebrow, Icon, Notice } from '../components/ui';
import { CurrentLuck } from './LuckTimeline';
import { ElementChart, PillarGrid } from './SajuSnapshot';

export type SajuReply={executionStatus:string;conversationId?:string;consultationId:string;readingId:string;uncertaintyFlags?:string[];inlineResult?:{dayMaster:string|null;pillars:FullSajuResult['pillars'];elements:FullSajuResult['elements'];currentFlow?:SajuCurrentFlow};interpretation?:{messageId:string;content:string}|null;partialError?:{code:string}};
export function SajuInline({result,pending,onRetry}:{result:SajuReply;pending:boolean;onRetry:()=>void}) {const flow=result.inlineResult?.currentFlow;return <section className="tarot-inline saju-inline" aria-label="저장된 사주 결과"><Eyebrow>YOUR SAJU STORY</Eyebrow><h3 className="section-heading" style={{margin:'16px 0 24px'}}>{result.inlineResult?.dayMaster?`나의 중심 기운, ${result.inlineResult.dayMaster}`:'태어난 날의 흐름을 기록했어요'}</h3>{result.inlineResult?.pillars&&<div className="saju-inline-data"><PillarGrid pillars={result.inlineResult.pillars}/><div className="saju-inline-summary"><h4>오행의 균형</h4><ElementChart value={result.inlineResult.elements} compact/><h4>함께 살펴볼 흐름</h4><CurrentLuck timing={flow?.timing} compact/>{flow?.sewoon?<p>{flow.sewoon.year}년 · 입춘 기준 · {flow.sewoon.pillar.heavenlyStem}{flow.sewoon.pillar.earthlyBranch}</p>:<p>이 상담에는 올해의 흐름 정보가 아직 없어요.</p>}{flow?.monthlyFortune&&<p>월별 흐름 · 절기 기준 · {flow.monthlyFortune.pillar.heavenlyStem}{flow.monthlyFortune.pillar.earthlyBranch}</p>}{!flow?.timing?.luck&&flow?.daewoon&&<small>대운은 {flow.daewoon.forward?'순행':'역행'} · 출생 후 {flow.daewoon.startYears}년 {flow.daewoon.startMonths}개월부터 시작</small>}</div></div>} {!!result.uncertaintyFlags?.length&&<p className="section-note">출생시간이나 날짜 경계에 따라 확정하지 못한 부분이 있어요. 자세한 결과에서 가능한 범위를 함께 살펴보세요.</p>}{result.executionStatus==='PARTIAL'&&<Notice>원국과 계산 결과는 저장되었어요. 해석을 다시 받아도 저장된 결과를 그대로 사용해요.</Notice>}<div className="tarot-actions"><Link to={`/reading/${result.consultationId}`}>사주 자세히 보기 <Icon name="arrow" size={15}/></Link><button type="button" disabled={pending} onClick={onRetry}><Icon name="history" size={15}/>사주 해석 다시 받기</button></div></section>;}
