// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryLibrary } from '../../src/features/MemoryLibrary';
const mocked=vi.hoisted(()=>({list:vi.fn(),update:vi.fn(),remove:vi.fn()}));
vi.mock('../../src/lib/service',()=>({service:{listMemories:mocked.list,updateMemory:mocked.update,deleteMemory:mocked.remove}}));
vi.mock('../../src/features/session',()=>({useSession:()=>({session:{user:{id:'user-1'}}}),useProfile:()=>({data:{memory_enabled:true}}),errorMessage:(error:unknown)=>error instanceof Error?error.message:'오류'}));
const memories=[{id:'global-person',content:'친구 별칭은 별이',scope:'GLOBAL',character_id:null,category:'PERSON',subject:'친구',disabled_at:null,importance:2,created_at:'2026-09-20'}, {id:'bomi-goal',content:'이직을 준비하고 있어',scope:'CHARACTER',character_id:'BOMI',category:'GOAL',subject:'목표',disabled_at:null,importance:2,created_at:'2026-09-20'}, {id:'sani-person',content:'산이에게 말한 친구',scope:'CHARACTER',character_id:'SANI',category:'PERSON',subject:'친구',disabled_at:null,importance:2,created_at:'2026-09-20'}];
function mount(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryLibrary/></QueryClientProvider>);}
beforeEach(()=>{mocked.list.mockReset().mockResolvedValue(memories);mocked.update.mockReset().mockResolvedValue(undefined);mocked.remove.mockReset().mockResolvedValue(undefined);HTMLDialogElement.prototype.showModal=vi.fn(function(this:HTMLDialogElement){this.setAttribute('open','');});HTMLDialogElement.prototype.close=vi.fn();});afterEach(cleanup);
describe('memory management',()=>{
 it('filters category and character without modifying stored memories',async()=>{mount();await screen.findByText('친구 별칭은 별이');fireEvent.change(screen.getByLabelText('기억의 종류'),{target:{value:'PERSON'}});fireEvent.change(screen.getByLabelText('함께 기억하는 사람'),{target:{value:'SANI'}});expect(screen.queryByText('친구 별칭은 별이')).toBeNull();expect(screen.getByText('산이에게 말한 친구')).toBeTruthy();expect(mocked.update).not.toHaveBeenCalled();});
 it('disables use without deleting the memory or overwriting content',async()=>{mount();await screen.findByText('친구 별칭은 별이');fireEvent.click(screen.getAllByText('이 기억 사용하지 않기')[0]);await waitFor(()=>expect(mocked.update).toHaveBeenCalledWith('global-person',{disabled_at:expect.any(String)}));expect(mocked.remove).not.toHaveBeenCalled();expect(mocked.update.mock.calls[0][1]).not.toHaveProperty('content');});
 it('confirms the selected category and only deletes its visible members',async()=>{mount();await screen.findByText('친구 별칭은 별이');fireEvent.change(screen.getByLabelText('기억의 종류'),{target:{value:'PERSON'}});fireEvent.click(screen.getByText('이 종류의 기억 삭제'));expect(mocked.remove).not.toHaveBeenCalled();const dialog=screen.getByRole('dialog');fireEvent.click(within(dialog).getByText('2개 삭제'));await waitFor(()=>expect(mocked.remove).toHaveBeenCalledTimes(2));expect(mocked.remove).toHaveBeenCalledWith('global-person');expect(mocked.remove).toHaveBeenCalledWith('sani-person');expect(mocked.remove).not.toHaveBeenCalledWith('bomi-goal');});
 it('keeps only failed deletion items available for retry',async()=>{mocked.remove.mockImplementation(async(id:string)=>{if(id==='sani-person')throw new Error('연결 실패');});mount();await screen.findByText('친구 별칭은 별이');fireEvent.change(screen.getByLabelText('기억의 종류'),{target:{value:'PERSON'}});fireEvent.click(screen.getByText('이 종류의 기억 삭제'));fireEvent.click(within(screen.getByRole('dialog')).getByText('2개 삭제'));await waitFor(()=>expect(within(screen.getByRole('dialog')).getByText('1개 삭제')).toBeTruthy());expect(within(screen.getByRole('dialog')).queryByText('친구 별칭은 별이')).toBeNull();expect(within(screen.getByRole('dialog')).getByText('산이에게 말한 친구')).toBeTruthy();});
});
